`trio_ayncio` now contains an `allow_asyncio` wrapper which allows you to
seamlessly mix asyncio and trio semantics::

    from trio_asyncio import run allow_asyncio

    async def main():
        print("Sleeping 1")
        await asyncio.sleep(1)
        print("Sleeping 2")
        await trio.sleep(1)

    run(allow_asyncio, main)

The problem with this solution is that Trio's cancellations will no longer
be converted to asyncio's `CancelledError` within asyncio code. This may or
may not be an issue for your code.
